name: TestRail Upload Results
description: Uploads test results to TestRail
inputs:
  command:
    description: 'Command to run - parse_junit or parse_robot'
    required: true
  testrail-host:
    description: 'TestRail Host'
    required: true
  testrail-user:
    description: 'TestRail User'
    required: true
  testrail-password:
    description: 'TestRail Password'
    required: true
  testrail-project-name:
    description: 'TestRail Project name'
    required: true
  report-path:
    description: 'Report filepath'
    required: true
  testrun-title:
    description: 'Testrun Title'
    required: true
  project-name:
    description: 'Project Name'
    required: true
  close-run:
    description: 'Close the newly created run'
    required: false
  case-matcher:
    description: 'Mechanism to match cases between the report and TestRail.'
    required: false
  suite-id:
    description: 'Suite ID to submit results to.'
    required: false
  suite-name:
    description: 'Suite name to submit results to.'
    required: false
  run-id:
    description: 'Run ID for the results they are reporting (otherwise the tool will attempt to create a new run).'
    required: false
  plan-id:
    description: 'Plan ID with which the Test Run will be associated.'
    required: false
  config-ids:
    description: 'Comma-separated configuration IDs to use along with Test Plans (i.e.: 34,52)'
    required: false
  milestone-id:
    description: 'Milestone ID to which the Test Run should be associated to.'
    required: false
  section-id:
    description: 'Section ID to create new sections with test cases under.'
    required: false
  run-description:
    description: 'Summary text to be added to the test run.'
    required: false
  case-fields:
    description: 'List of case fields and values for new test cases creation. Usage: --case-fields type_id:1 --case-fields priority_id:3'
    required: false
  result-fields:
    description: 'List of result fields and values for test results creation. Usage: --result-fields custom_field_a:value1 --result-fields custom_field_b:3'
    required: false
  allow-ms:
    description: 'Allows using milliseconds for elapsed times.'
    required: false
  special-parser:
    description: 'Optional special parser option for specialized JUnit reports.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - -h
    - ${{ inputs.testrail-host }}
    - --project
    - ${{ inputs.testrail-project-name }}
    - -u
    - ${{ inputs.testrail-user }}
    - -p
    - ${{ inputs.testrail-password }}
    - ${{ inputs.command }}
    - -f
    - ${{ inputs.report-path }}
    - --title
    - ${{ inputs.testrun-title }}
